*** Read the file with your modules:
load MSET-INT . 
in exe-30.maude

*** RUNTEST EXERCISE 30
                          
red mult(4, none) .                       *** should give 0

red mult(4, 1 2 3 4 5 6 3 4 5 12 44 4) .  *** should give 3

red mult(7, 1 2 3 4 5 6 8 9)  .           *** should give 0

red mult(1, 5 7 3 1 8) .                  *** should give 1

red max(1 2 3 4 5 6 3 4 5 12 44 4) .      *** should give 44

red max(345) .                            *** should give 345

red max(4 5 6 7 1 2 3 4 5 6 7 3) .        *** should give 7

red empty?(none) .                        *** should give true

red empty?(345) .                         *** should give false       

red empty?(2 1 3 1) .                     *** should give false

red none >mul none .                      *** should give false

red 1969 >mul none .                      *** should give true

red 1 2 3 4 5 1 2 3 >mul 1 3 5 6 .        *** should give false 

red 3 4 7 7 >mul 1 2 2 0 4 1 -3 7 7 .     *** should give true

red 3 4 7 7 >mul 1 2 2 0 4 4 1 -3 7 7 .   *** should give false
