*** Read the file with your modules:
in oblig2.maude


red first(nil) .        *** should give error, ie. first(nil) of kind [List]

red first(200 2) .      *** 200

red first(1 2 3 4 5) .  *** 1

red first(12) .         *** 12


*** RUNTEST EXERCISE 26 

red empty?(nil) .          *** true 

red empty?(6) .            *** false 

red empty?(1 5 2 6) .      *** false 

red rest(1) .              *** nil 

red rest(5 8 12 9 4 3) .   *** 8 12 9 4 3

red reverse(nil) .         *** nil

red reverse(200 2) .       *** give back 2 200

red reverse(12) .          *** 12

red reverse(1 2 3 4 5) .   *** 5 4 3 2 1

red max(12) .              *** 12

red max(10 2 2003) .       *** 2003

red max(1 2 3 4 5) .       *** 5 

red max(5 7 6) .           *** 7

red isSorted(nil) .        *** true

red isSorted(2003) .       *** true

red isSorted(5 7 6) .      *** false 

red isSorted(1 2 3 4 5) .  *** true




*** RUNTEST EXERCISE 27 

red comesBeforeIn(1, 2, nil) .   *** false

red comesBeforeIn(1, 2, 1 2 3) .   *** true 

red comesBeforeIn(2, 1, 1 2 3) .   *** false 

red comesBeforeIn(4, 2, 3 5 4 6 7 1 3 2 4) .   *** true 

red 1 2 3 4 >lex 1 2 3 .   *** true

red 2 3 4 >lex 1 2 3 4 .  *** true

red 1 >lex 1 0 .          *** false 

red 2 5 6 >lex 2 4 678 12 .  *** true  




*** RUNTEST EXERCISE 28 

red 'h' 'e' prefixOf 'h' 'e' 'l' 'l' 'o' .    *** true

red 'h' 'a' prefixOf 'h' 'e' 'l' 'l' 'o' .    *** false

red 'h' 'e' 'l' 'l' 'o' prefixOf 'h' 'i' .    *** false

red 'h' '?' prefixOf 'h' 'e' 'l' 'l' 'o' .    *** true

red 'h' '?' prefixOf 'h' 'i' .                *** true

red '?' 'a' prefixOf 'h' 'e' 'y' .            *** false

red '?' '?' '?' prefixOf 'h' 'i' .            *** false 

red 'h' 'e' substringOf 'h' 'e' 'l' 'l' 'o' . *** true

red 'l' 'l' substringOf 'e' 'l' 'l' .         *** true 

red 'l' 'a' substringOf 'h' 'e' 'l' 'l' 'o' . *** false 

red 'h' 'e' 'y' substringOf 'h' 'i' .         *** false

red 'h' '?' 'l' substringOf 'h' 'e' 'l' 'l' . *** true 

red '?' 'y' substringOf 'h' 'e' 'y' .         *** true 

red 'i' '?' '?' substringOf 'h' 'i' .         *** true 



*** RUNTEST EXERCISE 30
                          
red mult(4, none) .                       *** should give 0

red mult(4, 1 2 3 4 5 6 3 4 5 12 44 4) .  *** should give 3

red mult(7, 1 2 3 4 5 6 8 9)  .           *** should give 0

red mult(1, 5 7 3 1 8) .                  *** should give 1

red max(1 2 3 4 5 6 3 4 5 12 44 4) .      *** should give 44

red max(345) .                            *** should give 345

red max(4 5 6 7 1 2 3 4 5 6 7 3) .        *** should give 7

red empty?(none) .                        *** should give true

red empty?(345) .                         *** should give false       

red empty?(2 1 3 1) .                     *** should give false

red none >mul none .                      *** should give false

red 1969 >mul none .                      *** should give true

red 1 2 3 4 5 1 2 3 >mul 1 3 5 6 .        *** should give false 

red 3 4 7 7 >mul 1 2 2 0 4 1 -3 7 7 .     *** should give true

red 3 4 7 7 >mul 1 2 2 0 4 4 1 -3 7 7 .   *** should give false


*** NO RUNTEST FOR EXERCISE 32 SINCE WE DONT KNOW HOW OBJ OR MSG ARE DECLARED 

*** RUNTEST EXERCISE 37 

red insertSort(1 4 2 3)        *** should give 1 2 3 4

red insertSort(5 4 3 2 1)      *** should give 1 2 3 4 5 

red insertSort(1 2 3 4)        *** should give 1 2 3 4