*** Read the file with your modules:
load LIST-INT . 
in exe-26.maude


red first(nil) .        *** should give error, ie. first(nil) of kind [List]

red first(200 2) .      *** 200

red first(1 2 3 4 5) .  *** 1

red first(12) .         *** 12


*** RUNTEST EXERCISE 26 

red empty?(nil) .          *** true 

red empty?(6) .            *** false 

red empty?(1 5 2 6) .      *** false 

red rest(1) .              *** nil 

red rest(5 8 12 9 4 3) .   *** 8 12 9 4 3

red reverse(nil) .         *** nil

red reverse(200 2) .       *** give back 2 200

red reverse(12) .          *** 12

red reverse(1 2 3 4 5) .   *** 5 4 3 2 1

red max(12) .              *** 12

red max(10 2 2003) .       *** 2003

red max(1 2 3 4 5) .       *** 5 

red max(5 7 6) .           *** 7

red isSorted(nil) .        *** true

red isSorted(2003) .       *** true

red isSorted(5 7 6) .      *** false 

red isSorted(1 2 3 4 5) .  *** true
